import Link from 'next/link'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About',
  description: 'Learn about our AI-powered blog and how we create content.',
}

export default function AboutPage() {
  const siteName = process.env.NEXT_PUBLIC_SITE_NAME || 'AutoBlog AI'

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      <nav style={{ borderBottom: '1px solid var(--border)', background: 'var(--bg2)', position: 'sticky', top: 0, zIndex: 50 }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none' }}>
            <div style={{ width: 28, height: 28, background: 'var(--amber)', borderRadius: 6, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>✦</div>
            <span style={{ fontFamily: 'var(--font-playfair)', fontSize: 16, fontWeight: 700, color: 'var(--amber)' }}>{siteName}</span>
          </Link>
          <div style={{ display: 'flex', gap: 20 }}>
            <Link href="/" style={{ fontSize: 13, color: 'var(--text2)', textDecoration: 'none' }}>Home</Link>
            <Link href="/blog" style={{ fontSize: 13, color: 'var(--text2)', textDecoration: 'none' }}>Blog</Link>
          </div>
        </div>
      </nav>

      <div style={{ maxWidth: 780, margin: '0 auto', padding: '64px 24px' }}>
        <h1 style={{ fontFamily: 'var(--font-playfair)', fontSize: '2.5rem', fontWeight: 700, marginBottom: 16 }}>
          About {siteName}
        </h1>
        <p style={{ fontSize: '1.1rem', color: 'var(--text2)', lineHeight: 1.8, marginBottom: 40, borderBottom: '1px solid var(--border)', paddingBottom: 40 }}>
          Your daily source for AI-curated insights across technology, finance, business, and more.
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontSize: '1.4rem', fontWeight: 700, marginBottom: 12 }}>What We Do</h2>
            <p style={{ fontSize: '1rem', color: 'var(--text2)', lineHeight: 1.8 }}>
              {siteName} is an AI-powered publication that monitors trending topics across the web and produces in-depth, thoroughly researched articles on the subjects that matter most right now. Our AI pipeline scans Google Trends, Reddit, HackerNews, and dozens of RSS feeds every two hours, identifies high-interest topics, and produces 2,500–3,500 word articles covering the full picture.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontSize: '1.4rem', fontWeight: 700, marginBottom: 12 }}>How Our Content is Created</h2>
            <p style={{ fontSize: '1rem', color: 'var(--text2)', lineHeight: 1.8, marginBottom: 16 }}>
              Every article on {siteName} is written by a large language model (Claude by Anthropic) trained on a vast corpus of web content, books, and authoritative sources. The AI follows strict editorial guidelines:
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {[
                '✦ Factual, well-researched content drawn from multiple sources',
                '✦ Clear, jargon-free writing accessible to general audiences',
                '✦ Balanced perspectives on complex or contested topics',
                '✦ Full SEO structure: headings, summaries, FAQs, and citations',
                '✦ Fresh content published four times daily at optimal reading hours',
              ].map(item => (
                <div key={item} style={{ display: 'flex', gap: 12, padding: '10px 14px', background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 14, color: 'var(--text2)', lineHeight: 1.6 }}>
                  {item}
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontSize: '1.4rem', fontWeight: 700, marginBottom: 12 }}>Editorial Disclaimer</h2>
            <div style={{ background: 'var(--bg3)', border: '1px solid var(--border)', borderRadius: 10, padding: '20px 22px', fontSize: 14, color: 'var(--text2)', lineHeight: 1.8 }}>
              The articles on {siteName} are generated by artificial intelligence. While we strive for accuracy, AI-generated content may contain errors or outdated information. Always verify important information with primary sources before making decisions. Some articles may contain affiliate links — if you purchase through these links, we may earn a small commission at no extra cost to you.
            </div>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontSize: '1.4rem', fontWeight: 700, marginBottom: 12 }}>Categories We Cover</h2>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
              {['Technology', 'AI & ML', 'Finance', 'Business', 'Health', 'Gaming', 'Crypto', 'Science'].map(cat => (
                <Link key={cat} href={`/blog/category/${cat.toLowerCase().replace(' & ', '-')}`}
                  style={{ padding: '8px 18px', background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 20, fontSize: 13, color: 'var(--text)', textDecoration: 'none', fontWeight: 500 }}>
                  {cat}
                </Link>
              ))}
            </div>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontSize: '1.4rem', fontWeight: 700, marginBottom: 12 }}>Contact</h2>
            <p style={{ fontSize: '1rem', color: 'var(--text2)', lineHeight: 1.8 }}>
              For advertising, sponsorships, or general inquiries, reach out at{' '}
              <a href={`mailto:hello@${(process.env.NEXT_PUBLIC_SITE_URL || 'yourdomain.com').replace('https://', '')}`}
                style={{ color: 'var(--amber)', textDecoration: 'underline' }}>
                hello@yourdomain.com
              </a>
            </p>
          </section>
        </div>
      </div>

      <footer style={{ borderTop: '1px solid var(--border)', background: 'var(--bg2)', padding: '24px', textAlign: 'center' }}>
        <p style={{ color: 'var(--text2)', fontSize: 12 }}>© {new Date().getFullYear()} {siteName}</p>
      </footer>
    </div>
  )
}
